services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #      Setting up initial script
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      #      Note that I've mapped this to port 13316. This is because I already have a MySQL server running on my machine on port 3306.
      - "13316:3306"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'